name: EconomyShop
version: @VERSION@
author: onebone
api: [1.0.0]
main: me.onebone.economyshop.EconomyShop
depend: [EconomyAPI]

commands:
  shop:
    description: Shop management command
    usage: /shop <create|remove> [item[:damage]] [amount] [price] [side]
    permission: economyshop.command.shop;economyshop.command.shop.create;economyshop.command.shop.remove;
  buy:
    description: Buying command
    usage: /buy [amount]
    permission: economyshop.command.buy
    

permissions:
  economyshop:
    description: Includes all permissions of EconomyShop
    children:
      economyshop.command:
        description: Allows player to use all commands of EconomyShop
        children:
          economyshop.command.shop:
            description: Allows player to use /shop
            children:
              economyshop.command.shop.create:
                description: Allows player to use /shop create
              economyshop.command.shop.remove:
                description: Allows player to use /shop remove
          economyshop.command.buy:
            description: Allows player to use /buy
            default: true
      economyshop.purchase:
        description: Allows player to purchase item from shop
        default: true
      economyshop.create:
        description: Allows player to create shop
      economyshop.break:
        description: Allows player to break shop
